### ISSUE TITLE
Swagger just hangs

### ISSUE THREAD

**Issue by jorgv** [hackolade/Swagger#24]
Hello, We just subscribed to Hackolade, we are trying to test the swagger reverse engineer, but with a file around 1Mb it just hangs for hours. We tried in different environments Linux and Windows with powerful machines. Not sure how to proceed. thanks

**Comment by pdesmarets** [comment]
As discussed in the ticket you opened with our helpdesk, this is certainly not related to the file size.  Let's continue the conversation in the helpdesk thread.
